(add-ext-dir (concat-path elisp-dir "apel"))
(add-ext-dir (concat-path elisp-dir "flim"))
(add-ext-dir (concat-path elisp-dir "bbdb"))
(add-ext-dir (concat-path elisp-dir "emacs-w3m"))
(add-ext-dir (concat-path elisp-dir "emacs-w3m" "shimbun"))
(add-ext-dir (concat-path elisp-dir "gnus" "lisp"))
(add-ext-dir (concat-path elisp-dir "magit"))
(add-ext-dir (concat-path elisp-dir "magit" "contrib"))
(add-ext-dir (concat-path elisp-dir "smex"))
(add-ext-dir (concat-path elisp-dir "slime"))
(add-ext-dir (concat-path elisp-dir "slime" "contrib"))
(add-ext-dir (concat-path elisp-dir "undo-tree"))
(add-ext-dir (concat-path elisp-dir "yasnippet"))
(add-ext-dir (concat-path elisp-dir "zf-mode"))
(add-ext-dir (concat-path elisp-dir "zf-mode" "bundled"))

(require 'magit)
