(add-ext-dir (concat-path elisp-dir "apel"))
(add-ext-dir (concat-path elisp-dir "auctex"))
(add-ext-dir (concat-path elisp-dir "auctex" "preview"))
(add-ext-dir (concat-path elisp-dir "auctex" "style"))
(add-ext-dir (concat-path elisp-dir "auto-complete"))
(add-ext-dir (concat-path elisp-dir "bbdb"))
(add-ext-dir (concat-path elisp-dir "chicken-scheme"))
(add-ext-dir (concat-path elisp-dir "flim"))
(add-ext-dir (concat-path elisp-dir "emacs-w3m"))
(add-ext-dir (concat-path elisp-dir "emacs-w3m" "shimbun"))
(add-ext-dir (concat-path elisp-dir "gnus" "lisp"))
(add-ext-dir (concat-path elisp-dir "magit"))
(add-ext-dir (concat-path elisp-dir "magit" "contrib"))
(add-ext-dir (concat-path elisp-dir "org-mode" "lisp"))
(add-ext-dir (concat-path elisp-dir "org-mode" "contrib" "lisp"))
(add-ext-dir (concat-path elisp-dir "smex"))
(add-ext-dir (concat-path elisp-dir "slime"))
(add-ext-dir (concat-path elisp-dir "slime" "contrib"))
(add-ext-dir (concat-path elisp-dir "undo-tree"))
(add-ext-dir (concat-path elisp-dir "yasnippet"))
(add-ext-dir (concat-path elisp-dir "zf-mode"))
(add-ext-dir (concat-path elisp-dir "zf-mode" "bundled"))
